/**
 * Generates the root deno.jsonc for scaffolded applications.
 * @module
 */

import type { TemplateContext } from "../domain/types.ts";

/**
 * Renders a fresh deno.jsonc file for a newly initialized app.
 */
export function renderDenoJsonc(context: TemplateContext): string {
  return `{
  // Generated by deno-app-scaffold-cli on ${context.generatedAtIso}
  "fmt": {
    "lineWidth": 88,
    "indentWidth": 2,
    "useTabs": false,
    "semiColons": true,
    "singleQuote": false,
    "proseWrap": "preserve",
    "trailingCommas": "onlyMultiLine",
    "operatorPosition": "nextLine"
  },
  "lint": {
    "rules": {
      "tags": ["recommended"]
    }
  },
  "compilerOptions": {
    "strict": true
  },
  "exports": {
    ".": "./src/mod.ts"
  },
  "tasks": {
    "test": "deno test --allow-read --coverage=coverage ./tests",
    "coverage": "deno coverage coverage --lcov --output=coverage/lcov.info && deno coverage coverage",
    "coverage:check": "deno coverage coverage --summary",
    "bench": "deno bench ./benchmarks",
    "fmt": "deno fmt",
    "fmt:check": "deno fmt --check",
    "lint": "deno lint ./src ./tests ./benchmarks ./examples",
    "check": "deno check ./src/mod.ts",
    "ci": "deno task fmt:check && deno task lint && deno task check && deno task test"
  },
  "exclude": [".*", "coverage"]
}
`;
}
