import type { TemplateContext } from "@scaffold/types";

export const metadata = { outputPath: "deno.jsonc" };

export default function (context: TemplateContext): string {
  return `{
  // Generated by deno-app-scaffold-cli on ${context.generatedAtIso}
  "name": "${context.packageName}",
  "version": "0.0.1-rc.0",
  "fmt": {
    "lineWidth": 88,
    "indentWidth": 2,
    "useTabs": false,
    "semiColons": true,
    "singleQuote": false,
    "proseWrap": "preserve",
    "trailingCommas": "onlyMultiLine",
    "operatorPosition": "nextLine"
  },
  "lint": {
    "rules": {
      "tags": ["recommended"]
    }
  },
  "compilerOptions": {
    "strict": true
  },
  "exports": {
    ".": "./src/mod.ts"
  },
  "tasks": {
    "test": "deno test --allow-read --coverage=coverage ./tests",
    "bench": "deno bench ./benchmarks",
    "fmt": "deno fmt",
    "lint": "deno lint ./src ./tests ./benchmarks ./examples",
    "check": "deno check ./src/mod.ts",
    "ci": "deno task fmt && deno task lint --fix && deno task check && deno task test"
  },
  "exclude": [".*", "coverage"]
}
`;
}
